In [40]:
import torch
import numpy as np

# tensor属性

In [3]:
a = torch.tensor([1,2,3],dtype=int)
a

tensor([1, 2, 3])

In [4]:
a.dtype

torch.int64

In [6]:
b = torch.tensor([4,5,6],dtype = float)
b

tensor([4., 5., 6.], dtype=torch.float64)

In [8]:
tensor = torch.tensor([[1,2,3],
                       [4,5,6]])

In [13]:
'维度:',tensor.ndim,'形状:',tensor.shape,'形状:',tensor.shape

('维度:', 2, '形状:', torch.Size([2, 3]), '形状:', torch.Size([2, 3]))

# 数据生成

In [14]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [15]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [16]:
torch.rand(3,4)

tensor([[0.7058, 0.3558, 0.4543, 0.8608],
        [0.2498, 0.8903, 0.6426, 0.7600],
        [0.2724, 0.8927, 0.7314, 0.2603]])

In [18]:
# 0-10之间的随机整数
torch.randint(0,10,(2,3))

tensor([[2, 9, 6],
        [8, 3, 7]])

In [20]:
# 正态分布
torch.randn(3,4)

tensor([[-1.0305,  0.5153,  0.2813,  0.8438],
        [-0.7272,  1.2327,  0.0423, -1.7637],
        [ 0.4193, -0.4195,  0.0852, -1.2661]])

In [21]:
a = torch.tensor([[1,2],
                  [3,4],
                  [5,6]])

In [23]:
b = torch.rand_like(a,dtype=float)
b

tensor([[0.9620, 0.0556],
        [0.3181, 0.5652],
        [0.9196, 0.3964]], dtype=torch.float64)

In [33]:
# reshape
c = a.view(6)
c

tensor([1, 2, 3, 4, 5, 6])

In [37]:
c[0]

tensor(1)

In [39]:
# 获取数值
c[0].item()

1

# 和numpy转换

In [43]:
tensor = torch.tensor([[1,2],
                      [3,4],
                      [5,6]])
array = np.array(tensor)
array

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int64)

In [42]:
array = np.array([1,2,3])
tensor = torch.tensor(array)
tensor

tensor([1, 2, 3], dtype=torch.int32)