In [1]:
import torch
import numpy as np

# 基本运算操作

In [17]:
a = torch.randint(1,5,(2,3))
b = torch.randint(1,5,(2,3))
a,b

(tensor([[3, 3, 1],
         [4, 3, 3]]),
 tensor([[1, 3, 1],
         [4, 2, 2]]))

In [18]:
a+b

tensor([[4, 6, 2],
        [8, 5, 5]])

In [19]:
torch.add(a,b)

tensor([[4, 6, 2],
        [8, 5, 5]])

In [20]:
# 这里下划线表示a = a + b。
a.add_(b)
a

tensor([[4, 6, 2],
        [8, 5, 5]])

In [26]:
a = torch.ones(3,4)
a.dtype

torch.float32

In [32]:
tensor = torch.arange(12).view(4,3)
tensor.dtype

torch.int64

In [33]:
# 类型不一样时候，矩阵相乘会报错，用.float()进行转换
a.matmul(tensor.float())

tensor([[18., 22., 26.],
        [18., 22., 26.],
        [18., 22., 26.]])

In [36]:
# 转置
tensor,tensor.T

(tensor([[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]),
 tensor([[ 0,  3,  6,  9],
         [ 1,  4,  7, 10],
         [ 2,  5,  8, 11]]))

In [38]:
sample = torch.rand(3,4)
sample

tensor([[0.6331, 0.9594, 0.4337, 0.7949],
        [0.3055, 0.5531, 0.8793, 0.5486],
        [0.7871, 0.6207, 0.2410, 0.9510]])

In [48]:
# 求和，平均值，中位数
torch.sum(sample),torch.mean(sample),torch.median(sample)

(tensor(7.7074), tensor(0.6423), tensor(0.6207))

In [43]:
torch.min(sample),torch.max(sample)

(tensor(0.2410), tensor(0.9594))

In [45]:
# 最大最小值所在索引
torch.argmin(sample),torch.argmax(sample)

(tensor(10), tensor(1))

In [52]:
# 开方
torch.sqrt(sample)

tensor([[0.7957, 0.9795, 0.6586, 0.8916],
        [0.5527, 0.7437, 0.9377, 0.7407],
        [0.8872, 0.7879, 0.4909, 0.9752]])

In [53]:
# 平方
sample**2

tensor([[0.4008, 0.9205, 0.1881, 0.6319],
        [0.0933, 0.3060, 0.7731, 0.3009],
        [0.6196, 0.3853, 0.0581, 0.9045]])

# 数据索引

In [54]:
tensor = torch.arange(2,14)
tensor

tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [55]:
tensor[2]

tensor(4)

In [56]:
tensor[1:4]

tensor([3, 4, 5])

In [62]:
# 根据索引号取值
tensor[[1,11]]

tensor([ 3, 13])